// This file was auto-generated by Fern from our API Definition.

import type * as AshleyLavizadehApi from "../index.js";

export interface PlantCreatedPayload {
    event?: PlantCreatedPayload.Event;
    timestamp?: string;
    data?: AshleyLavizadehApi.PlantResponse;
}

export namespace PlantCreatedPayload {
    export const Event = {
        PlantCreated: "plant.created",
    } as const;
    export type Event = (typeof Event)[keyof typeof Event];
}
