// This file was auto-generated by Fern from our API Definition.

import type * as AshleyLavizadehApi from "../index.js";

export interface PostPlantUpdatedPayload {
    event?: PostPlantUpdatedPayload.Event;
    timestamp?: string;
    data?: AshleyLavizadehApi.PlantResponse;
}

export namespace PostPlantUpdatedPayload {
    export const Event = {
        PlantUpdated: "plant.updated",
    } as const;
    export type Event = (typeof Event)[keyof typeof Event];
}
