// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as AshleyLavizadehApi from "../../../index.js";

export declare namespace PlantClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Everything about your Plants
 */
export class PlantClient {
    protected readonly _options: NormalizedClientOptions<PlantClient.Options>;

    constructor(options: PlantClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {AshleyLavizadehApi.Plant} request
     * @param {PlantClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AshleyLavizadehApi.MethodNotAllowedError}
     *
     * @example
     *     await client.plant.addPlant({
     *         name: "Fern",
     *         category: "Indoor",
     *         tags: ["green", "leafy"],
     *         status: "available"
     *     })
     */
    public addPlant(
        request: AshleyLavizadehApi.Plant,
        requestOptions?: PlantClient.RequestOptions,
    ): core.HttpResponsePromise<AshleyLavizadehApi.PlantResponse> {
        return core.HttpResponsePromise.fromPromise(this.__addPlant(request, requestOptions));
    }

    private async __addPlant(
        request: AshleyLavizadehApi.Plant,
        requestOptions?: PlantClient.RequestOptions,
    ): Promise<core.WithRawResponse<AshleyLavizadehApi.PlantResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AshleyLavizadehApiEnvironment.Default,
                "plant",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AshleyLavizadehApi.PlantResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 405:
                    throw new AshleyLavizadehApi.MethodNotAllowedError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AshleyLavizadehApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/plant");
    }

    /**
     * @param {AshleyLavizadehApi.Plant} request
     * @param {PlantClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AshleyLavizadehApi.BadRequestError}
     * @throws {@link AshleyLavizadehApi.NotFoundError}
     *
     * @example
     *     await client.plant.updatePlant({
     *         name: "Fern",
     *         category: "Indoor",
     *         tags: ["green", "leafy"],
     *         status: "sold"
     *     })
     */
    public updatePlant(
        request: AshleyLavizadehApi.Plant,
        requestOptions?: PlantClient.RequestOptions,
    ): core.HttpResponsePromise<AshleyLavizadehApi.PlantResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updatePlant(request, requestOptions));
    }

    private async __updatePlant(
        request: AshleyLavizadehApi.Plant,
        requestOptions?: PlantClient.RequestOptions,
    ): Promise<core.WithRawResponse<AshleyLavizadehApi.PlantResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AshleyLavizadehApiEnvironment.Default,
                "plant",
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AshleyLavizadehApi.PlantResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AshleyLavizadehApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 404:
                    throw new AshleyLavizadehApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.AshleyLavizadehApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/plant");
    }

    /**
     * Filter plants based on their current status.
     *
     * @param {AshleyLavizadehApi.SearchPlantsByStatusRequest} request
     * @param {PlantClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.plant.searchPlantsByStatus()
     */
    public searchPlantsByStatus(
        request: AshleyLavizadehApi.SearchPlantsByStatusRequest = {},
        requestOptions?: PlantClient.RequestOptions,
    ): core.HttpResponsePromise<AshleyLavizadehApi.PlantResponse[]> {
        return core.HttpResponsePromise.fromPromise(this.__searchPlantsByStatus(request, requestOptions));
    }

    private async __searchPlantsByStatus(
        request: AshleyLavizadehApi.SearchPlantsByStatusRequest = {},
        requestOptions?: PlantClient.RequestOptions,
    ): Promise<core.WithRawResponse<AshleyLavizadehApi.PlantResponse[]>> {
        const { status } = request;
        const _queryParams: Record<string, unknown> = {
            status: status != null ? status : undefined,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AshleyLavizadehApiEnvironment.Default,
                "plant/search/status",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AshleyLavizadehApi.PlantResponse[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AshleyLavizadehApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/plant/search/status");
    }

    /**
     * Filter plants based on associated tags.
     *
     * @param {AshleyLavizadehApi.SearchPlantsByTagsRequest} request
     * @param {PlantClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.plant.searchPlantsByTags()
     */
    public searchPlantsByTags(
        request: AshleyLavizadehApi.SearchPlantsByTagsRequest = {},
        requestOptions?: PlantClient.RequestOptions,
    ): core.HttpResponsePromise<AshleyLavizadehApi.PlantResponse[]> {
        return core.HttpResponsePromise.fromPromise(this.__searchPlantsByTags(request, requestOptions));
    }

    private async __searchPlantsByTags(
        request: AshleyLavizadehApi.SearchPlantsByTagsRequest = {},
        requestOptions?: PlantClient.RequestOptions,
    ): Promise<core.WithRawResponse<AshleyLavizadehApi.PlantResponse[]>> {
        const { tags } = request;
        const _queryParams: Record<string, unknown> = {
            tags,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AshleyLavizadehApiEnvironment.Default,
                "plant/search/tags",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AshleyLavizadehApi.PlantResponse[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AshleyLavizadehApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/plant/search/tags");
    }

    /**
     * Retrieve a plant's details by its ID.
     *
     * @param {AshleyLavizadehApi.GetPlantByIdRequest} request
     * @param {PlantClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.plant.getPlantById({
     *         plantId: 1
     *     })
     */
    public getPlantById(
        request: AshleyLavizadehApi.GetPlantByIdRequest,
        requestOptions?: PlantClient.RequestOptions,
    ): core.HttpResponsePromise<AshleyLavizadehApi.PlantResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getPlantById(request, requestOptions));
    }

    private async __getPlantById(
        request: AshleyLavizadehApi.GetPlantByIdRequest,
        requestOptions?: PlantClient.RequestOptions,
    ): Promise<core.WithRawResponse<AshleyLavizadehApi.PlantResponse>> {
        const { plantId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AshleyLavizadehApiEnvironment.Default,
                `plant/${core.url.encodePathParam(plantId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AshleyLavizadehApi.PlantResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AshleyLavizadehApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/plant/{plantId}");
    }
}
