// This file was auto-generated by Fern from our API Definition.

export const AshleyLavizadehApiEnvironment = {
    Default: "https://api.plantstore.dev/v3",
} as const;

export type AshleyLavizadehApiEnvironment = typeof AshleyLavizadehApiEnvironment.Default;
